Traceback (most recent call last):
  File "train_gpt2_refactored.py", line 62, in <module>
    tokenizer = PreTrainedTokenizerFast(
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 116, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: expected `,` or `}` at line 2 column 10
E0209 20:35:59.379319 139665459308352 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 1543975) of binary: /home/jovyan/miniconda3/envs/fokin_HCNN/bin/python
Traceback (most recent call last):
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jovyan/miniconda3/envs/fokin_HCNN/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_gpt2_refactored.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-09_20:35:59
  host      : hopper-h100-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1543975)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
